import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app 👋',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="container">
          <div>
            <p>My Blog</p>
            <p>{metadata.description}</p>
          </div>
        </header>
        <main className="container">{children}</main>
        <footer>
          <div className="container">
            <p>Created with Next.js</p>
            <p>Justus &copy; 2023</p>
          </div>
        </footer>
      </body>
    </html>
  )
}
